### ISSUE TITLE
推荐集成这个雪花ID

### ISSUE THREAD

**Issue by yitter** [masastack/MASA.Contrib#1]
https://github.com/yitter/IdGenerator

**Comment by doddgu** [comment]
好的，我们会评估一下，谢谢

**Comment by doddgu** [comment]
暂定后续增加一个IdGenerator接口，由用户自行指定。届时将会提供IdGenerator的示例

**Comment by zhenlei520** [comment]
This problem has been fixed, if there are no other problems, this pr will be closed after 3 days @yitter

**Comment by yitter** [comment]
only a suggestion. you own it.

**Comment by zhenlei520** [comment]
OK, thank you very much for your suggestion
